### Testing REST file for login and signup, maybe also in the future will be used to view the user

### ---------------------- SIGN-UP-REQUEST
POST http://0.0.0.0:8000/api/signup/
Content-Type: application/json

{"username": "fakeshaked1", "email": "fake.shaked1@gmai.com" ,"password": "12341234", "profile": {"friends": []}}

### ---------------------- LOG-IN-REQUEST

POST http://0.0.0.0:8000/api/login/
Content-Type: application/json

{"username": "fakevova1", "password": "12341234"}

### ---------------------- USER-AUTHENTICATION-REQUEST

GET http://0.0.0.0:8000/api/test-token/
Content-Type: application/json
Authorization: token 231977513fb46554489432160ee289df7d5a6fdc


### ---------------------- SEND-FRIEND-REQUEST

POST http://0.0.0.0:8000/api/friend-requests/
Content-Type: application/json

{"to_user": "3", "from_user": "1"}


### ---------------------- GET-FRIEND-REQUESTS

GET http://0.0.0.0:8000/api/friend-requests/
Content-Type: application/json



### ---------------------- GET-USER-BY-TOKEN

GET http://0.0.0.0:8000/api/get-user/
Content-Type: application/json
Authorization: token 231977513fb46554489432160ee289df7d5a6fdc


### ---------------------- DELETE FRIEND REQUESTS




### ---------------------- GET-USER-BY-ID

GET http://0.0.0.0:8000/api/minimal-user/2/