### Testing REST file for login and signup, maybe also in the future will be used to view the user

### ---------------------- SIGN-UP-REQUEST
POST http://0.0.0.0:8000/api/signup/
Content-Type: application/json

{"username": "fakevova3", "email": "fake.vova3@gmai.com" ,"password": "12341234", "profile": {"friends": []}}

### ---------------------- LOG-IN-REQUEST

POST http://0.0.0.0:8000/api/login/
Content-Type: application/json

{"username": "fakevova1", "password": "12341234"}

### ---------------------- USER-AUTHENTICATION-REQUEST

GET http://0.0.0.0:8000/api/test-token/
Content-Type: application/json
Authorization: token 345f72712d9ccc18bf207216004167f2f5b4f26a


### ---------------------- SEND-FRIEND-REQUEST

POST http://0.0.0.0:8000/api/friend-requests/
Content-Type: application/json

{"to_user": "2", "from_user": "3"}


### ---------------------- GET-USER-BY-TOKEN

GET http://0.0.0.0:8000/api/get-user/
Content-Type: application/json
Authorization: token 345f72712d9ccc18bf207216004167f2f5b4f26a