# Generated by Django 4.2.7 on 2023-11-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=256)),
                ('feeder', models.CharField(max_length=256)),
                ('amount', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('food_choice', models.CharField(choices=[('wet', 'Wet'), ('dry', 'Dry')], default='dry', max_length=4)),
            ],
        ),
    ]
