# Generated by Django 4.2.7 on 2023-11-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daisyfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
